config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  root 'search#index'
  get 'reports/index'

  resources :researchers, only: [:index, :show] do
    member do
      get :coauthors
    end
  end

  get 'reports/publications_by_year'
  get 'reports/publications_by_country'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Onto-Mongo
    == csrf_meta_tags

    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_include_tag 'https://www.gstatic.com/charts/loader.js'
    == javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.navbar-default
      .container-fluid
        /! Brand and toggle get grouped for better mobile display
        .navbar-header
          button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"  Onto-Mongo
        /! Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              a href="#"
                | Link
                span.sr-only (current)
            li = link_to 'Researchers', researchers_path
            li.dropdown
              a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                | Reports
                span.caret
              ul.dropdown-menu
                li = link_to 'Publications by Year', reports_publications_by_year_path
                li = link_to 'Publications by Country', reports_publications_by_country_path
        /! /.navbar-collapse
      /! /.container-fluid

    == yield